version: '3.9'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: registro-gastos-bot
    restart: unless-stopped
    ports:
      - '${PORT:-3001}:3000'
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    networks:
      - backend
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

networks:
  backend:
    external: true
